### ISSUE TITLE
Ban / kick doesn't work

### ISSUE THREAD

**Issue by Kromanic** [qbcore-framework/qb-adminmenu#10]
Hi so when ever i had a wave of hackers that came into my server I was trying  use the admin panel to ban ppl but every time I put in a response and enter it tell's me not enough reason... i don't know why it was doing that, but beside the point I had to go threw my txadmin to ban the ppl

**Comment by BerkieBb** [comment]
This has been fixed with https://github.com/qbcore-framework/qb-core/commit/842c7c93012f332833b32995ab426d24bedc6eb8
