### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by SharkyFP** [qbcore-framework/qb-adminmenu#110]
**Describe the bug**
I've got a bug with /reporttoggle command where it should give you 2 options. Either Toggle reports ON or OFF but I only get OFF. Since /staffchat is connected to that staff members also can't chat on the server. I checked console ingame and server log console and I found no bugs.

**To Reproduce**
1. Use in-game /reporttoggle
2. Check if it gives to options when typing it twice
3. Got only "You are not receiving reports"
4. No error

**Expected behavior**
When using /reporttoggle
1. "You are not receiving reports"
2. "You are receiving reports"

**Screenshots**
( I spammed /reporttoggle for refrence to see what I get )
![image](https://user-images.githubusercontent.com/70804183/156894369-9410c795-e540-4882-9b6b-09f711a229de.png)

**Questions (please complete the following information):**
 - When you last updated: Last update was yesterday  but it was same as 20 days ago
 - Are you using custom resource? which ones? Nothing that conflicts with admin ( Only txAdmin )
 - Have you renamed `qb-` to something custom? No

**Additional context**
Staff chat doesn't work either since it is connected to reporttoggle

**Comment by Yonatannn** [comment]
check if you have this functions in qb-core/server/functions.lua

```
function QBCore.Functions.IsOptin(source)
    local src = source
    local license = QBCore.Functions.GetIdentifier(src, 'license')
    if QBCore.Functions.HasPermission(src, 'admin') then
        return QBCore.Config.Server.PermissionList[license].optin
    end
end
```

**Comment by SharkyFP** [comment]
Yes I have that function.

**Comment by SharkyFP** [comment]
/report and /reporttoggle is fixed. I gave myself admin again and it worked.

There is still a issue with /staffchat where I get this in console
![image](https://user-images.githubusercontent.com/70804183/157354552-4da3a3ce-7dbd-44b4-8619-e581713988b7.png)
