### ISSUE TITLE
[BUG] /reportr only works for me as server owner

### ISSUE THREAD

**Issue by Brusein** [qbcore-framework/qb-adminmenu#112]
**Describe the bug**
when my admins or others with god permission attempt to /reportr (respond to a /report) they message is not sent to chat. But for me alone I can /reportr and reply to the /report done by a player.

**To Reproduce**
Have someone /report anything
Have and admin/god who is not server owner try /reportr and reply

**Expected behavior**
anyone with Admin perms and above should be able to /reportr to assist a player.

**Comment by GhzGarage** [comment]
Follow the new permissions guidelines and this will work just fine
