### ISSUE TITLE
Re: Admin Permissions

### ISSUE THREAD

**Issue by CollapsedLegacy** [qbcore-framework/qb-adminmenu#113]
Hello, I recently installed the whole of qbcore and it seems that the admin perms don't work. I follow the steps and add my license etc to the database but it seems that it still doesn't let any of my admins who I've set to "god" save. When I override it by setting the admin menu to the role of user and set staff as admins, it doesn't save either. 

Can't wait to hear back from you guys.

**Comment by itsyaboydavey** [comment]
hello i am having the same issue i copy the right license and the id and name and rank god no caps and it fails to work

**Comment by CollapsedLegacy** [comment]
> hello i am having the same issue i copy the right license and the id and name and rank god no caps and it fails to work

Did yours randomly just fix? Mine has

**Comment by itsyaboydavey** [comment]
> > hello i am having the same issue i copy the right license and the id and name and rank god no caps and it fails to work
> 
> Did yours randomly just fix? Mine has

I downgraded the core to 1.0.0 and the dB works and the ace perms work as well

**Comment by CollapsedLegacy** [comment]
I didn't need to do anything, it started working randomly.

**Comment by parham-tehrani** [comment]
im suffering from the same problem now, i check the database , the users are set to admin, but when they come in the city, they're not admin and i have to give them the admin role using /admin every time they log in !

**Comment by Purenoiz** [comment]
I've tried every guide and video I could find. Nothing works. Anyone have any idea?

**Comment by GhzGarage** [comment]
Follow the new permissions guidelines and this will work just fine. Reference here: https://github.com/qbcore-framework/txAdminRecipe/blob/3840defa89a45118e8528168bf9670888a0710bc/server.cfg#L92
