### ISSUE TITLE
qb-adminmenu Vehicle Section "disabled"

### ISSUE THREAD

**Issue by RazanAliPlays** [qbcore-framework/qb-adminmenu#115]
I was working on new ideas for pdm and using the vehicle shop to "buy" cars as a admin but for some reason now when I try to hit buy for free, the command pops up as if I have no access to this command. Anyone know any fixes for that?

**Comment by GhzGarage** [comment]
Follow the new permissions guidelines and this will work just fine. Reference here: https://github.com/qbcore-framework/txAdminRecipe/blob/3840defa89a45118e8528168bf9670888a0710bc/server.cfg#L92
