### ISSUE TITLE
[BUG] Admin Spectator Mode

### ISSUE THREAD

**Issue by Molicheu** [qbcore-framework/qb-adminmenu#116]
**Describe the bug**
When you open up the admin menu, and you go to player management, then select spectate player, it teleports you to the player, makes you invisible and etc but it doesn't set your player in spectator mode. You're able to freely walk around and away from the player that's supposed to be spectated. The function "NetworkSetInSpectatorMode" is not being activated.

**To Reproduce**
1. Go to 'Admin menu'
2. Click on 'Player management then Spectate'
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**
For my player that's doing the spectating, hover over the player selected to spectate 

**Screenshots**
https://streamable.com/9tebjc

**Questions (please complete the following information):**
 - When you last updated: 2 hours ago
 - Are you using custom resource? which ones? None
 - Have you renamed `qb-` to something custom? No

**Additional context**

**Comment by GhzGarage** [comment]
Pretty sure this has never worked tbh but i'll mark it as to-do
