### ISSUE TITLE
[BUG] SCRIPT ERROR: server.lua:94: attempt to concatenate a nil value (field 'discord')

### ISSUE THREAD

**Issue by erpofficial** [qbcore-framework/qb-adminmenu#117]
**Describe the bug**

SCRIPT ERROR: @qb-adminmenu/server/server.lua:94: attempt to concatenate a nil value (field 'discord')

**To Reproduce**
1. Open admin menu
2. Kick
3. Give reason
4. Kick and then check console for the error

**Screenshots**

![image](https://user-images.githubusercontent.com/102900480/161553728-136ac1e1-8951-4f70-a083-6b7682cd6311.png)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]  ::: I am tryng leatest  update
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] ::::::: No
 - Have you renamed `qb-` to something custom? [e.g. yes/no] :::: No

**Additional context**

**Comment by GhzGarage** [comment]
#119
