### ISSUE TITLE
[BUG] Setting permissions in /admin menu

### ISSUE THREAD

**Issue by P4R4NORM4L** [qbcore-framework/qb-adminmenu#123]
**Describe the bug**
So setting permissions in /admin under player management --> USER --- Permissions does not save.

**To Reproduce**
For example, I am set to god in the Server.cfg but in the admin menu I am set to user. If I set my permission to god on the menu and restart my game I have to redo it because it does not save for some reason.

**Expected behavior**
Setting a players permission should stay whether or not the player restarts his/her game!

**Screenshots**
No screenshots really necessary

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? which ones? Not for the admin menu no
 - Have you renamed `qb-` to something custom? No I have not

**Additional context**
I have followed the guidelines in the discord channel
https://discord.com/channels/831626422232678481/852748355838410762/961046399816966174

add_ace resource.qb-core command allow # Allow qb-core to execute commands
add_ace qbcore.god command allow # Allow all commands

add_principal qbcore.god group.admin # Error proof
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

add_principal identifier.fivem:5222421 qbcore.god #p4r4

Am I missing anything ?

**Comment by FrogCF** [comment]
Hi,

We are having the same trouble after keep setting myself to Admin everytime fly in the city?

**Comment by xKazukixv** [comment]
When is put my id my name and licence and god it dont give me admin menu

**Comment by FrogCF** [comment]
Hello, 

After spending few hour's, 



Copy my code into your cfg.config 

## Permissions ##

# Resources
add_ace resource.qb-core command allow # Allow qb-core to execute commands

# Gods
add_ace qbcore.god command allow # Allow all commands

# Inheritance
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

#add_principal identifier.{{principalMasterIdentifier}} qbcore.god <- doesn't exist yet, change the generated one below to qbcore.god
add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin name 
add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin Name
add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin Name
add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin Name
add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin Name
add_principal identifier.fivem:Your Numbers  qbcore.mod # Your Admin Name

**PLEASE NOTE**
qbcore.god isn't getting full permissions at this time. qb-core is aware of this problem they are working on a fix.

Please use admin only at this time or mod

**WHEN YOU DONE THE ABOVE THEN SAVE IT RESTART YOUR SERVER!**

LOGIN your city and try /noclip and spawn vehicle and should work any problems come back i'll try help

**Comment by xKazukixv** [comment]
What do i put in this add_principal identifier.fivem:Your Numbers qbcore.admin # Your Admin Name

**Comment by xKazukixv** [comment]
I did the license and it still dont work

**Comment by xKazukixv** [comment]
Do you know how long till the admin mneuis fixed

**Comment by imkuroneko** [comment]
The `qb-adminmenu` works with the database so, you will need to save your license on the `permissions` table (as `god`);

Just doing on this way worked for me... and I deleted from my copy of the menu the section of give permissions because only works temporally (it doesn't save on the DB and I don't know so much of lua for modify/fix that)

**Comment by P4R4NORM4L** [comment]
That means you do not have the latest version as there is no permissions table in the new QB-core.They removed it

**Comment by xKazukixv** [comment]
oh ok

**Comment by xKazukixv** [comment]
i put my permissions to god and i still dont have the admin menu

**Comment by P4R4NORM4L** [comment]
did you follow this ?
https://github.com/qbcore-framework/qb-adminmenu/issues/123#issuecomment-1094285624

**Comment by xKazukixv** [comment]
and it still dont work

**Comment by P4R4NORM4L** [comment]
Then it must be a bug

**Comment by P4R4NORM4L** [comment]
try setting this
add_principal qbcore.admin group.admin

**Comment by P4R4NORM4L** [comment]
in server.cfg

**Comment by xKazukixv** [comment]
do i put it under gods or Inheritance

**Comment by P4R4NORM4L** [comment]
it's inheritance
qbcore admin will get same perms as group admin but I don't know if it'll work so

**Comment by xKazukixv** [comment]
It dident work

**Comment by xKazukixv** [comment]
Do you know what would be the bug

**Comment by Brianelvio** [comment]
> That means you do not have the latest version as there is no permissions table in the new QB-core.They removed it

You say this but the sql file in the repo still contains it?

**Comment by P4R4NORM4L** [comment]
https://discord.com/channels/831626422232678481/852748355838410762/958862662396174347

**Comment by P4R4NORM4L** [comment]
They didn't get a chance to remove it yet

**Comment by P4R4NORM4L** [comment]
join the qb-core discord then click on the link

**Comment by Staticdevvv** [comment]
When i set my self as god i dont get the menu

**Comment by FrogCF** [comment]
> When i set my self as god i dont get the menu

Hello, please, share an image or the way you have set out your permissions. I'll be happier to assist you with your question or issues.

**Comment by Staticdevvv** [comment]
I put it how you sent   https://github.com/qbcore-framework/qb-adminmenu/issues/123#issuecomment-1094285624

**Comment by Staticdevvv** [comment]
and it wont work for me

**Comment by FrogCF** [comment]
@Staticdevvv, 

Please, follow this one edit to make it easier for you all to understand. 

Wrote out for you just after adding your own information in the missing boxes. 

#   ____  ____   _____               
#  / __ \|  _ \ / ____|              
# | |  | | |_) | |     ___  _ __ ___ 
# | |  | |  _ <| |    / _ \| '__/ _ \
# | |__| | |_) | |___| (_) | | |  __/
#  \___\_\____/ \_____\___/|_|  \___|

## You CAN edit the following:
endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"
sv_maxclients 48
set steam_webApiKey "none"
sets tags "default, deployer, qbcore, qb-core"

## You MAY edit the following:
sv_licenseKey ""
sv_hostname ""
sets sv_projectName ""
sets sv_projectDesc ""
sets locale "en-US" 
load_server_icon myLogo.png
set sv_enforceGameBuild 2372
set mysql_connection_string ""

# Voice config
setr voice_useNativeAudio true
setr voice_useSendingRangeOnly true
setr voice_defaultCycle "GRAVE"
setr voice_defaultVolume 0.3
setr voice_enableRadioAnim 1
setr voice_syncData 1

# QBCore locale config
setr qb_locale "en"

# QBCore UseTarget
setr UseTarget true

# These resources will start by default.
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
ensure baseevents

# QBCore & Extra stuff
ensure qb-core
ensure [qb]
ensure [standalone]
ensure [voice]
ensure [defaultmaps]
ensure [vehicles]
ensure [addon]


## Permissions ##

# Resources
add_ace resource.qb-core command allow # Allow qb-core to execute commands

# Gods
add_ace qbcore.god command allow # Allow all commands
add_principal qbcore.god group.admin # Error proof
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

# Inheritance
add_principal identifier.fivem:0000000 qbcore.god #yourname
add_principal identifier.discord:000000000 qbcore.admin #yourname
add_principal identifier.fivem:00000000 qbcore.god #yourname
add_principal identifier.fivem:0000000 qbcore.mod #yourname
add_principal identifier.discord:00000000 qbcore.god #yourname
add_principal identifier.fivem:0000000 qbcore.god #yourname
add_principal identifier.discord:00000000 qbcore.mod #yourname

# Gods
add_ace qbcore.god command allow # Allow all commands

# Inheritance
add_principal qbcore.god group.admin # Allow gods access to the main admin group used to get all default permissions
add_principal qbcore.god qbcore.admin # Allow gods access to admin commands
add_principal qbcore.admin qbcore.mod # Allow admins access to mod commands

# END OF THE CONFIG!
