### ISSUE TITLE
Noclip

### ISSUE THREAD

**Issue by Progamerboys** [qbcore-framework/qb-adminmenu#128]
i cant open map on noclip

**Comment by xanten11** [comment]
> i cant open map on noclip

if you dont want any lock on map i did it bu removeing 


    DisableAllControlActions(0)
    DisableAllControlActions(1)
    DisableAllControlActions(2)
    in noclip.lua in client

**Comment by xanten11** [comment]
DisableAllControlActions(0) will alow map use but also out  things just remove it or comment out
