### ISSUE TITLE
[BUG] Spactate not working

### ISSUE THREAD

**Issue by TweakyGaming** [qbcore-framework/qb-adminmenu#130]
**Describe the bug**
Currently Spectate is not working
Apparently it also has something to do with the distance if someone is in my render radius it works.

**Comment by ARSSANTO** [comment]
yes with a certain distance its working perfect but after cross distance its just fall from the maps

**Comment by EpicV-Roleplay** [comment]
I just stay at the same position only become invisible

**Comment by iafondo** [comment]
Iam having same issue only works if you are in range!!!!

**Comment by GhostLegionRP** [comment]
Same problem

**Comment by Blaze0341** [comment]
same

**Comment by Ashember** [comment]
> I just stay at the same position only become invisible

same issue
