### ISSUE TITLE
[BUG] /reports & /staffchat not working

### ISSUE THREAD

**Issue by Ubeyds0206** [qbcore-framework/qb-adminmenu#132]
The commands are showing up as suggestion but when i use them it does nothing. I tested multiple chats and none of them showed any different results.

There are no errors whatsoever. I have the admin permissions set correctly.

**Comment by Magnitrude** [comment]
I have same issue

**Comment by linus-jansson** [comment]
Same issue still..

**Comment by linus-jansson** [comment]
I think I found the issue. I believe https://github.com/qbcore-framework/qb-adminmenu/blob/64872470f828a8aeb0b175f334f62a92dfc02b57/server/server.lua#L172
is the issue.. Somehow, you need to optin for staffchat and admin reports somehow? I bet that if you remove that `optin` check it works

**Comment by r0adra93** [comment]
confirmed error is present
reporttoggle does not work.

**Comment by TomTheDark** [comment]
> 

I also confirm

**Comment by Maanusss** [comment]
Buenas, alguna novedad?
