### ISSUE TITLE
[BUG] Spectate doesn't work with Onesync Infinity

### ISSUE THREAD

**Issue by izmystic** [qbcore-framework/qb-adminmenu#137]
**Describe the bug**
When you spectate a player thats out of the infinty range, itll make you invisible, and youll just fall out of the map

**To Reproduce**
1. Be out of the infinty range of a player
2. open adminmenu
3. spectate player

**Expected behavior**
It should just spectate the player

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 30 minutes ago
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] no
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Comment by FrogCF** [comment]
Hi, 

I have checked this and able to spectate player without the area please try latest version with many bugs fixed. 

Please upload video showing us where this happens?

This will help to re-try reproduce the issue?

**Comment by erikmeyer08** [comment]
I just tried the latest version and still having the same issue.
My character disappears like it moved to the other player but the camera just stays where it was and doesn't move.

**Comment by FrogCF** [comment]
Hello,

Does this happen when you are Spectate in added ymap? 

I'm trying reproduced this current problem?

**Comment by erikmeyer08** [comment]
No I'm in legion square park
![20220501133307_1](https://user-images.githubusercontent.com/43043270/166157369-199160ba-0c41-41a5-964f-5d2bfc6d2d7f.jpg)
![20220501133321_1](https://user-images.githubusercontent.com/43043270/166157372-d70237bb-f478-4d1d-975c-27f73ecdb6c7.jpg)
![20220501133324_1](https://user-images.githubusercontent.com/43043270/166157377-f8c00102-0cf8-4539-9f99-25390cb438a3.jpg)

**Comment by FrogCF** [comment]
I'll check it out get back to you with my findings thank you for images its
most appreciated and helpful.

**Comment by erikmeyer08** [comment]
The latest update seems to have resolved this issue. Thanks.

**Comment by FrogCF** [comment]
> The latest update seems to have resolved this issue. Thanks.

That's brilliant I'm glad you are able to use QB-core without any further issues.

**Comment by erikmeyer08** [comment]
So I lied.. it works 1 time when you first load into the server but then doesn't work after that.

**Comment by AshleyJ1994** [comment]
I can second that, issues with onesync and spectating here too.

**Comment by SmithyPD** [comment]
Same for us as well, does the same as the pictures provided, in range of player or not.

**Comment by ZumieFiasco** [comment]
Yeah same, spectate is pretty much useless since the range is so short. Really hope for a fix soon! This wasn't an issue a few months ago so its strange that it is now.

**Comment by FrogCF** [comment]
I can confirm since the latest updated version spectate doesn't seem to work very good anymore. I tested on number of levels and sometimes get black screen after logout back in again.

**Comment by iafondo** [comment]
Spectate works inside certain range if you go in range or goto then spectate it works, dumbfix would change code to gotoand spectate at the same time, ez fixed tele back as always still xp

**Comment by Blaze0341** [comment]
Having the same issue...there a fix for this?

**Comment by Sk33t80** [comment]
I am still having the spectate issues, anyone else?

**Comment by Ashember** [comment]
yes I'm not able to spectate either same as above disa0ear but don't actually spectate

**Comment by AlphaCarry** [comment]
I have same problem too is it only with infinity? or without infinity?

**Comment by Ashember** [comment]
I can't get it to work at all, so it will have to be a tech that fixes it.. only reason I haven't fixed it cause it doesn't log when someone spectates

**Comment by iafondo** [comment]
easy fix:
client
`
RegisterNetEvent('qb-admin:client:spectate', function(targetPed, coords)
    local myPed = PlayerPedId()
    if not isSpectating then
        lastSpectateCoord = GetEntityCoords(myPed) -- save my last coords
        SetEntityCoords(myPed, coords.x, coords.y, coords.z)
        SetEntityVisible(myPed, false) -- Set invisible
        NetworkSetEntityInvisibleToNetwork(myPed, true) -- Set invisibility
        SetEntityCollision(myPed, false, false) -- Set collision
        SetEntityInvincible(myPed, true) -- Set invincible
        FreezeEntityPosition(myPed, true)
        Wait(1000)
        local targetplayer = GetPlayerFromServerId(targetPed)
        local target = GetPlayerPed(targetplayer)
        FreezeEntityPosition(myPed, false)
        NetworkSetInSpectatorMode(true, target) -- Enter Spectate Mode
        isSpectating = true
    else
        local targetplayer = GetPlayerFromServerId(targetPed)
        local target = GetPlayerPed(targetplayer)
        isSpectating = false
        NetworkSetInSpectatorMode(false, target) -- Remove From Spectate Mode
        NetworkSetEntityInvisibleToNetwork(myPed, false) -- Set Visible
        SetEntityCollision(myPed, true, true) -- Set collision
        SetEntityCoords(myPed, lastSpectateCoord) -- Return Me To My Coords
        SetEntityVisible(myPed, true) -- Remove invisible
        SetEntityInvincible(myPed, false) -- Remove godmode
        lastSpectateCoord = nil -- Reset Last Saved Coords
    end
end)
`
server
`
RegisterNetEvent('qb-admin:server:spectate', function(player)
    local src = source
    if QBCore.Functions.HasPermission(src, permissions['spectate']) or IsPlayerAceAllowed(src, 'command') then
        local targetped = GetPlayerPed(player)
        local coords = GetEntityCoords(targetped)
        TriggerClientEvent('qb-admin:client:spectate', src, player, coords)
        TriggerEvent('um-admin:log:playersEvent',src,"spectate","Spectate".."["..player.."]","black",player)
    else
        BanPlayer(src)
    end
end)
`

**Comment by iafondo** [comment]
`RegisterNetEvent('qb-admin:server:spectate', function(player)
    local src = source
    if QBCore.Functions.HasPermission(src, permissions['spectate']) or IsPlayerAceAllowed(src, 'command') then
        local targetped = GetPlayerPed(player)
        local coords = GetEntityCoords(targetped)
        TriggerClientEvent('qb-admin:client:spectate', src, player, coords)
        TriggerEvent('um-admin:log:playersEvent',src,"spectate","Spectate".."["..player.."]","black",player)
    else
        BanPlayer(src)
    end
end)`

**Comment by iafondo** [comment]
Easy fix:
[spectate.txt](https://github.com/qbcore-framework/qb-adminmenu/files/11143033/spectate.txt)

**Comment by 1mRAAAH** [comment]
Spectating is broken as of today
