### ISSUE TITLE
[BUG] Bans & kicks not working

### ISSUE THREAD

**Issue by Nepic999** [qbcore-framework/qb-adminmenu#139]
Bans and kicks appear not to be working for some odd reason,

I dont really understand why as I've had it working before the new update to the menu its self, if anyone can help me out with this it would be greatly appriciated :)

**Comment by FrogCF** [comment]
Hi, 
do you get any error messages when pressing F8 on your fiveM? 

do you get any error messages in the console?

**Comment by Nepic999** [comment]
> Hi, do you get any error messages when pressing F8 on your fiveM?
> 
> do you get any error messages in the console?

Nope, no error at all just wont let me kick / ban people

**Comment by NiftyLife** [comment]
Bans: You have to confirm the banlength with enter
Kicks: Working fine for me.

**Comment by FrogCF** [comment]
@NiftyLife 

The kick/ban working fine no problems here either. Did you fill out the box for the reason? 

https://easyupload.io/m/u6xp9p

It works totally fine no bugs!
