### ISSUE TITLE
[SUGGESTION] Have the ability to use ESC muscle when no clipped

### ISSUE THREAD

**Issue by erikmeyer08** [qbcore-framework/qb-adminmenu#141]
[SUGGESTION] Have the ability to use ESC muscle when no clipped.

**Comment by kywan** [comment]
same as #128 

in noclip.lua in client remove
DisableAllControlActions(0)
DisableAllControlActions(1)
DisableAllControlActions(2)

**Comment by erikmeyer08** [comment]
Thanks!
