### ISSUE TITLE
[BUG] /admincar it does not work with all cars

### ISSUE THREAD

**Issue by SamueleAbbate** [qbcore-framework/qb-adminmenu#146]
on some machines the error is `error.no_store_vehicle_garage` returned when you do the /admincar command the reason is quite simple: the script reads the machine name with spaces and this does not allow it to run correctly. luckily I have already solved this problem and just insert 
` vehname = vehname:gsub("%s+", "")
 vehname = string.gsub(vehname, "%s+", "")`
 
in the events.lua file as in the photo that I am attaching.
![adminmenuerror](https://user-images.githubusercontent.com/91976683/169712963-da8bb717-1c5f-405e-9a71-323393eced35.PNG)

**Comment by SWIFTDESIGNS** [comment]
From doing a bit of testing i believe my self its because some vehicles don't have vehiclelayouts.meta as all my vehicles that arn't working with /admincar don't have vehiclelayouts.meta's

**Comment by xenfovn** [comment]
update new version , this is old code

**Comment by iafondo** [comment]
heres the fix:
![sad](https://user-images.githubusercontent.com/85797833/179429818-21f4df44-cbd8-4422-9185-8cecebaad26f.png)

**Comment by amantu-qbit** [comment]
@SamueleAbbate @iafondo Did you made any PR with the fix?

**Comment by amantu-qbit** [comment]
Just Checked the code. only Vehicles which isn't in QBCore Vehicle.lua will not save.

**Comment by iafondo** [comment]
Unless a recent change was made since 3 weeks ago it wasnt, only after i added that code, and all my cars are in the vehicles. Tested multiple
