### ISSUE TITLE
Freeaim mode not working [BUG]

### ISSUE THREAD

**Issue by elmschaym** [qbcore-framework/qb-adminmenu#154]
Freeaim mode not working in bed object

![notworkingbed](https://user-images.githubusercontent.com/6017220/173185216-047a9ad8-d20d-4aba-94fb-f45a14b4af89.PNG)

**Comment by amantu-qbit** [comment]
@elmschaym It don't delete everything. It only deletes known props. and if the prop is known then it'll show the hash

**Comment by amantu-qbit** [comment]
It'll show like this

![image](https://user-images.githubusercontent.com/67361813/180784608-e7a9efad-2821-4fe3-b2cd-ebde12483ef7.png)
