### ISSUE TITLE
[BUG] I cant ban

### ISSUE THREAD

**Issue by R1see** [qbcore-framework/qb-adminmenu#159]
**Describe the bug**
A clear and concise description of what the bug is. A stranger to qbcore should be able to read your bug report and understand how to reproduce it themselves and understand how the feature should work normally.

**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Expected behavior**

**Screenshots**

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week]
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target]
 - Have you renamed `qb-` to something custom? [e.g. yes/no]

**Additional context**

**Comment by R1see** [comment]
When I try to ban I get this 
![image](https://user-images.githubusercontent.com/62443062/180299993-a3c98593-fcf6-48d2-b0fa-d2370beeccc6.png)

**Comment by amantu-qbit** [comment]
@R1see do you have the latest oxmysql? can you show us the code?
