### ISSUE TITLE
[SUGGESTION] Maxmods works on spawned vehicles.

### ISSUE THREAD

**Issue by Sylvernl88** [qbcore-framework/qb-adminmenu#160]
Maxmods only work on spawned vehicles if you have been in benny's

Love to see if you can use it directly on a spanwed vehicle

**Comment by xanten11** [comment]
interesting i thought it was working with spawned cars i will take a look if i can this week but i sware i thought it worked on all cars even /car spawned before Benny's

**Comment by xanten11** [comment]
but you said if you opened Benny's then did max mod it worked?

**Comment by Sylvernl88** [comment]
Yeah after benny's it works and it works on own cars but not on spawned cars

**Comment by xanten11** [comment]
i made this add on ill try and see if i can fix it soon but no promises
...im not the best lol

**Comment by Sylvernl88** [comment]
Np :) it still works

**Comment by xanten11** [comment]
i have sent a PR to fix this issue please review the Pull Request or wait for it to be added to the main branch

**Comment by xanten11** [comment]
@Sylvernl88  can you test and review please ?

**Comment by Sylvernl88** [comment]
Tommorow i am gonne check It
