### ISSUE TITLE
menu for customizing cars 

### ISSUE THREAD

**Issue by Skewwy** [qbcore-framework/qb-adminmenu#172]
would be great to have a menu to have access to change everything to do with cars. basically the same as Vmenu, all i have is "max car" so having stuff like change body parts, paint, rims.. all the must haves.

**Comment by i-kulgu** [comment]
> would be great to have a menu to have access to change everything to do with cars. basically the same as Vmenu, all i have is "max car" so having stuff like change body parts, paint, rims.. all the must haves.

Why not using qb-customs for this ?
Adminmenu isn't for vehicle modification.
