### ISSUE TITLE
Vehicle Spawn

### ISSUE THREAD

**Issue by Blaze0341** [qbcore-framework/qb-adminmenu#180]
Not sure what the issue is but its telling me it cannot index a null value at line 891:
label = QBCore.Shared.FirstToUpper(k),

It wont display any categories of vehicles and cant access them to spawn the vehicle. If I comment out the line, I can see blank spots where category labels are supposed to be, and click on them to then see the vehicles and spawn them.

**Comment by lyncstudio** [comment]
Could not replicate issue on most recent version of QBCore. Please try updating to the most recent version.

**Comment by Kingplexy** [comment]
I'm getting the same error updating did not fix

**Comment by Txc32** [comment]
same issue

**Comment by WixRoleplay** [comment]
> Not sure what the issue is but its telling me it cannot index a null value at line 891: label = QBCore.Shared.FirstToUpper(k),
> 
> It wont display any categories of vehicles and cant access them to spawn the vehicle. If I comment out the line, I can see blank spots where category labels are supposed to be, and click on them to then see the vehicles and spawn them.

replace LINE 890
label = QBCore.Shared.FirstToUpper(k),
WITH
label = k,
This should fix it.
Add me on Discord    Wick#5170
