### ISSUE TITLE
blips

### ISSUE THREAD

**Issue by djraymond** [qbcore-framework/qb-adminmenu#181]
add so that as usual when blips is on you can see it all over the map

**Comment by Smokiiee** [comment]
Yeah this is needed

**Comment by GarnetKatz** [comment]
You can do this by simply changing 

if distance < 0 then
                        distance = 0
to
if distance < 1 then
                        distance = 1

**Comment by Smokiiee** [comment]
if you use OneSync with infinity the blips do not work over the entire map but with it onsync legacy without infinity it works fine.
So is it a fix for it if using with legacy onesync

Ex pic. 
https://i.imgur.com/tIbvwbx.png

**Comment by AlphaCarry** [comment]
> if you use OneSync with infinity the blips do not work over the entire map but with it onsync legacy without infinity it works fine. So is it a fix for it if using with legacy onesync
> 
> Ex pic. https://i.imgur.com/tIbvwbx.png

Did you find how to fix?

**Comment by Smokiiee** [comment]
> > if you use OneSync with infinity the blips do not work over the entire map but with it onsync legacy without infinity it works fine. So is it a fix for it if using with legacy onesync
> > Ex pic. https://i.imgur.com/tIbvwbx.png
> 
> Did you find how to fix?

@AlphaCarry no. not that i know if. i myself did not do anything
