### ISSUE TITLE
Admin Menu Not working [BUG]

### ISSUE THREAD

**Issue by TankinTom** [qbcore-framework/qb-adminmenu#197]
**Describe the bug**
When pulling up the admin menu, and pulling up players, or vehicles, nothing appears, when reloading the menu, you get the following screenshot, and when re-installing, none of the developer options work, such as getting vectors, even the slash commands don't work

**To Reproduce**

**Expected behavior**
Everything should work fine

**Screenshots**
![20230109210017_1](https://user-images.githubusercontent.com/90729413/211461270-f7b406b4-7e55-4249-b6cc-e8deaf7b8a82.jpg)

**Questions (please complete the following information):**
 - When you last updated: [e.g. last week] 6-7 months
 - Are you using custom resource? which ones? [e.g. zdiscord, qb-target] N/A
 - Have you renamed `qb-` to something custom? [e.g. yes/no] no

**Additional context**
First noticed it last night, and then today it was still occurring.

**Comment by a-nonymou-s** [comment]
can u send me your script version ?

**Comment by PeterWasHere1** [comment]
the best thing i could tell you to do is update your qbcore to the newest qbcore as old ones normally tend to start getting outdated you can change your qbcore version inside of txadmin or the github.

**Comment by TankinTom** [comment]
> the best thing i could tell you to do is update your qbcore to the newest qbcore as old ones normally tend to start getting outdated you can change your qbcore version inside of txadmin or the github.

For it to work one day, but not the next, and we're on the most recent qb-core version, would mean it's something else.

**Comment by PeterWasHere1** [comment]
My issue was that I had stuff outdated and was running updated qb-core and my stuff still broke

**Comment by Tr1n14Lif3** [comment]
I'm having a similar issue …. I have already updated my artifacts and updated the qb-adminmenu script, yet still i cannot use my developer menu and vehicles don't show up in the vehicle menu, so I cant use it at all …. the last comment said they had something outdated, can someone help me figure out what I would need to update to try that solution -- I'm new to all this and have been learning as i go ... but have not had any issues with the admin menu until now, Please Help

**Comment by 5mSlrp** [comment]
@Tr1n14Lif3 same here, I'm pretty late but if you found a fix please lmk!

**Comment by 5mSlrp** [comment]
> > the best thing i could tell you to do is update your qbcore to the newest qbcore as old ones normally tend to start getting outdated you can change your qbcore version inside of txadmin or the github.
> 
> For it to work one day, but not the next, and we're on the most recent qb-core version, would mean it's something else.

Found a fix? Please tell me you have lol
