### ISSUE TITLE
[BUG] Admin Menu (Freeze)

### ISSUE THREAD

**Issue by Snakyermagerd** [qbcore-framework/qb-adminmenu#198]
When you freeze a player they can have the ability to spawn a car and break the freeze command and they are unfrozen.
**To Reproduce**
3. Use this item '....' (item's name from shared.lua if applicable)

**Comment by fghtiger2006** [comment]
cs

**Comment by PT-Mohamed-Hussein** [comment]
can you provide more information on how i can reproduce the error ?

**Comment by Snakyermagerd** [comment]
All I remember is freezing a player then having them spawn a car and the car could still move for some reason but if it disappeared for some reason they were frozen.
