### ISSUE TITLE
[BUG] Admin menu won't open, but commands work.

### ISSUE THREAD

**Issue by Cory-Freeman-SWES** [qbcore-framework/qb-adminmenu#201]
**Describe the bug**
/admin won't work, but all commands work.

**To Reproduce**
Try to open the admin menu.

**Expected behavior**
Admin menu is supposed to open.

**Screenshots**
None

**Questions (please complete the following information):**
 - When you last updated: 1 hour ago
 - Are you using custom resource? no
 - Have you renamed `qb-` to something custom? no

**Additional context**
I've went through the original cfg on tx, updated it to 2 different ones and it still won't work. i've tried everything I know to do. It wasn't working before so I did a fresh install of the script and it still won't work. That's when I started on the server.cfg. still no luck. No F8 errors or Console Errors

**Comment by ChristianBDev** [comment]
Are you an admin? if your a user it wont open, if your an admin or god it should allow it to open

**Comment by Cory-Freeman-SWES** [comment]
> Are you an admin? if your a user it wont open, if your an admin or god it should allow it to open

Yes, I am set in the config to admin. I even tried god and nothing happened.

**Comment by LilMochaZ** [comment]
He resolved it by reinstalling menuV. We still don’t understand what stopped it working all of a sudden as no changes were made to either scripts.
