### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by KelloTV** [qbcore-framework/qb-adminmenu#203]
So the admin menu has always worked perfectly fine. But while doing some work to the server, the dev options stopped working I cant do anything in there. The vehicle list doesn't show any categories anymore. You also cant fix vehicle, buy, remove vehicle, or max out. I've tried every player management group. ive looked through everything and i cant find the issue anywhere.

**Comment by Sharkiiie** [comment]
This is more of a question for the qbcore discord support channel.
But it's likely you have a syntax error in (at least) one of your core shared files. 
If you modified any of those files recently, double check them. If it's not that, open a thread on discord and someone will likely help

**Comment by FrogCF** [comment]
Hello, 
Please provide more information and error logs thanks.
