### ISSUE TITLE
[SUGGESTION] Fix for Spectate infinity (Tested)

### ISSUE THREAD

**Issue by iafondo** [qbcore-framework/qb-adminmenu#204]
Easy fix for infinity: (infinity is based of distance so yeah not an issue, by logic if you go out of range you cant spectate, but like this you teleport then you enter spectate in range) and yes this works
[spectate.txt](https://github.com/qbcore-framework/qb-adminmenu/files/11143033/spectate.txt)

Regards from KAOS Dev

**Comment by Fluffyss** [comment]
Fix doesnt work on my end...

**Comment by iafondo** [comment]
you are doing it wrong somewhere, it does work flawlessly
