### ISSUE TITLE
[BUG]SCRIPT ERROR in promise (unhandled rejection): Error: qb-adminmenu was unable to execute a query!, Field 'model' doesn't have a default value , INSERT INTO player_vehicle

### ISSUE THREAD

**Issue by DistrictCouncil13** [qbcore-framework/qb-adminmenu#205]
When ever i /admincar a vehicle im getting this popping up.

Not sure if it has to do with oxmysql or qb-admin-menu

All vehicles are in the Vehicles.lua file of qb-core so they are all in the database.

![Screenshot (704)](https://user-images.githubusercontent.com/130094816/234973611-6fce6c61-89a0-4e33-ba3b-bfb7ed9f8143.png)

**Comment by DistrictCouncil13** [comment]
All addon vehicles have been entered into the vehicles.lua of qb core, so they are all in the database

**Comment by PT-Mohamed-Hussein** [comment]
do u have any script that altered the player_vehicles table ?
bec it is looking for field called model

and ensure that the car is correctly added in QBCore.Shared.Vehicles
