### ISSUE TITLE
Performance Issue inside of Loop

### ISSUE THREAD

**Issue by AvarianKnight** [qbcore-framework/qb-adminmenu#224]
Some users inside of the txAdmin discord recently reported performance issues related to `qb-adminmenu` which was from this loop.

https://github.com/qbcore-framework/qb-adminmenu/blob/42f4f8972abdf3ac060a6d6a08cf499ee4470a7a/server/server.lua#L524-L548

![](https://i.imgur.com/Yhx7NL3.png)

There are functions that QB already has to deal with this (`GetQBPlayers`) to prevent constant serialization.

It might also be worth thinking about the data structure used to store player info and offer a "minimal qb player" that only has the users player data

**Comment by Mycroft-Studios** [comment]
should be fixed by #227
