### ISSUE TITLE
getting player coords in server script always yields (0, 0, 0)

### ISSUE THREAD

**Issue by Cappinator** [qbcore-framework/qb-adminmenu#30]
As the subject says, the following code in server.lua
`local coords = GetEntityCoords(GetPlayerPed(player.id))`
always yields (0, 0, 0), because GetPlayerPed(player.id) yields 0 instead of an actualy entity (even though the player.id is correct and present)

I first noticed this in qb-inventory, where creating a drop at the player's location would break because of this. I'm fairly new to lua and fivem code and haven't been able to figure out what's causing this.
Either nobody has noticed this (unlikely) or it's some kind of issue on my end that I can't figure out. Can anyone shed light on this please?

**Comment by PhilsBadMan** [comment]
Are you on onesync infinity?

**Comment by Cappinator** [comment]
I am not.

**Comment by PhilsBadMan** [comment]
That is most likely the issue. Pretty sure those natives can only be run server-side if using onesync infinity. You'll need to get coords client side.

**Comment by Cappinator** [comment]
Thanks, that fixed it!
