### ISSUE TITLE
[BUG] F8 Console Error Message

### ISSUE THREAD

**Issue by LateNightRP** [qbcore-framework/qb-adminmenu#48]
**Describe the bug**
Sometimes when you log into server the admin menu will throw a error code in the F8 console. This error code is random when it happens. If you log out of server and log back in the error code will go away and admin menu will work just fine. 

**To Reproduce**
This error message is random and no way to best reproduce it. It dose not happen every time you log in. Just random moments.

**Screenshots**
https://cdn.discordapp.com/attachments/859528707814981653/899283681036894259/qb-adminmeni_error.png

**Questions (please complete the following information):**
 - When you last updated: 1 week ago with recent updates as they come out
 - Are you using custom resource? which ones? None
 - Have you renamed `qb-` to something custom? No

**Comment by JericoFX** [comment]
Can you try to start menuv fisrt in the server. cfg

**Comment by LateNightRP** [comment]
You want me to try something like this?

ensure oxmysql
ensure qb-core
ensure menuv
ensure [qb]
ensure [standalone]
ensure [voice]

**Comment by JericoFX** [comment]
Yes

**Comment by LateNightRP** [comment]
Ok I will try it out
