### ISSUE TITLE
[SUGGESTION] ADD keys like F2 For noclip and F5 for the menu 

### ISSUE THREAD

**Issue by OxGhali** [qbcore-framework/qb-adminmenu#53]
[SUGGESTION] ADD keys like F2 For noclip and F5 for the menu

**Comment by jnccloud** [comment]
FYI, txadmin has a keybind for noclip and menu unless you're looking for something in qb-adminmenu specifically to bind quick.

**Comment by izMystic** [comment]
just use /binds
