### ISSUE TITLE
[BUG] Names / Blips are bugging and showing the wrong names and ids in their head

### ISSUE THREAD

**Issue by ivanribeirotrc** [qbcore-framework/qb-adminmenu#78]
**Describe the bug**
sometimes you activate the names and blips option in the admin menu and the name above the head as well as the id are wrong. getting name and id from other player

**To Reproduce**
1. activate the names and blips
2. see error

**Screenshots**
https://imgur.com/a/wSY9xD0 (I'm kenne not vinicius) 

**Questions (please complete the following information):**
 - When you last updated: yesterday by txadmin
 - Are you using custom resource? no only base of txadmin recipe
 - Have you renamed `qb-` to something custom? no

**Comment by MonkeyWhisper** [comment]
Cannot duplicate this issue, working as intended.

**Comment by linus-jansson** [comment]
I experience the same issue on a new install of qbus core..

![image](https://user-images.githubusercontent.com/30862662/181271152-25eb0b95-d456-4d95-9eee-c582be5da271.png)

I have ID number 5 not four
